### ISSUE TITLE
Save data

### ISSUE THREAD

**Issue by Eddiey538** [TopazTK/KH-ReFined#123]
I backed up my save data so I could continue from where i left off in re:fined, but when I installed it, it didn't show my save even when I put it back in the save data folder (with the png), is there another place where this mod reads save data?

**Comment by alexbambo** [comment]
@Eddiey538 Hey, I’m trying to actually get my Refined Save data working on the unmodded version of KH. Do you mind letting me know exactly where the original version save data is located? My refined data will not load on the unmodded version, so I wasn’t sure if it was because it was in the wrong location. When I get home, I can check where refined save data is found for you. Thanks!

**Comment by TopazTK** [comment]
Refer to #117. Closed.
